services:
- docker

language: java
jdk: openjdk8
python: 3

env:
  SPRING_PROFILES_ACTIVE: dev

addons:
  apt:
    packages:
    - jq
    - bash
    - curl
    - sudo
    - lsof
    - unzip
    - docker-ce
    - python-pip

before_install:
- sudo pip install httpie docker-compose >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 80

script:
- (./gradlew clean assemble bootRun || true) &
- wait_for 8080
- http :8080
- http :8080/api
- stop_any 8080 80

- (./gradlew bootRun || true) &
- wait_for 8080
- http :8080
- http :8080/api
- stop_any 8080 80

- java -jar build/libs/*.jar &
- wait_for 8080
- http :8080
- http :8080/api
- stop_any 8080 80

- bash build/libs/*.jar &
- wait_for 8080
- http :8080
- http :8080/api
- stop_any 8080 80

after_script:
- ./gradlew --stop || true
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
