language: java
jdk: oraclejdk8

env:
  SPRING_PROFILES_ACTIVE: dev

install: true
before_install:
# gradle
- curl -s "https://get.sdkman.io" | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- sdk selfupdate
- mkdir -p "$HOME/.sdkman/etc"
- touch "$HOME/.sdkman/etc/config"
- sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
- sdk use gradle
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- sudo apt -y update || true >/dev/null 2>&1
- sudo apt install -y --no-install-recommends bash curl python-pip >/dev/null 2>&1
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8081 8080 80

script:
- gradle clean assemble run &
- wait_for 8080 8000 8888
- stop_any 8080 8000 8888

- gradle run &
- wait_for 8080 8000 8888
- stop_any 8080 8000 8888

- java -jar build/libs/*.jar &
- wait_for 8080 8000 8888
- stop_any 8080 8000 8888

- bash build/libs/*.jar &
- wait_for 8080 8000 8888
- stop_any 8080 8000 8888

after_script:
- gradle --stop
