group: edge
dist: trusty
install: true
language: java
jdk: oraclejdk8
env:
  SPRING_PROFILES_ACTIVE: dev
  DOCKER_COMPOSE_VERSION: 1.12.0
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  # docker-compose
  - sudo rm -rf /usr/local/bin/docker-compose
  - export DOCKER_COPOSE_URL=https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)
  - curl -L $DOCKER_COPOSE_URL > docker-compose
  - chmod +x docker-compose
  - sudo mv -f docker-compose /usr/local/bin
script:
  - gradle clean assemble
  - docker-compose build --force-rm
after_script:
  - gradle --stop
  - docker-compose down -v --remove-orphans
cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
